### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by MackyCoders** [Deus-Scissuras/Unblocked-links-reborn#11]

**Comment by Deus-Scissuras** [comment]
Do you have a issue?

**Comment by Deus-Scissuras** [comment]
Is this MC programmerx Cause I have a suspicious that this is McProgrammerX
I’m not being Mean

**Comment by MackyCoders** [comment]
Nah i dont even know McProgrammerX

**Comment by MackyCoders** [comment]
Anyway i think ur quite cool nice name btw

**Comment by MackyCoders** [comment]
Also I am just a ordinary coder, joined github also i love javascript

**Comment by Deus-Scissuras** [comment]
Okay

**Comment by MackyCoders** [comment]
anyway i got 2 things

**Comment by MackyCoders** [comment]
why did u fork my home and two what is your organization link on GitHub

**Comment by MackyCoders** [comment]
@Deus-Scissuras

**Comment by Deus-Scissuras** [comment]
Just go on my page and click on my org and Fond ChatGpt stuff cool And like Ai Stuff And wanting to find a way to use chatgpt Without a API

**Comment by Deus-Scissuras** [comment]
I like Chatgpt

**Comment by Deus-Scissuras** [comment]
Oh Your home I was Bored and thought you were someone else

**Comment by Deus-Scissuras** [comment]
@MackyCoders

**Comment by MackyCoders** [comment]
yes

**Comment by MackyCoders** [comment]
@Deus-Scissuras what happened

**Comment by MackyCoders** [comment]
@Deus-Scissuras are u there

**Comment by Deus-Scissuras** [comment]
Look at the back

**Comment by MackyCoders** [comment]
the back?

**Comment by Deus-Scissuras** [comment]
Look at the message before I pinged you

**Comment by MackyCoders** [comment]
im new to GitHub + I dont see your org

**Comment by MackyCoders** [comment]
@[Deus-Scissuras](https://github.com/Deus-Scissuras)
Deus-Scissuras
[God of Breaches](https://github.com/Deus-Scissuras)
 · A piece of bread
Got Banned But I’m back
Owns this repository
Committed to this repository in the past week

That is what it shows

**Comment by MackyCoders** [comment]
@Deus-Scissuras https://github.com/RealJokers you mean that

**Comment by Deus-Scissuras** [comment]
Yes

**Comment by Deus-Scissuras** [comment]
Look here is the repo Link https://github.com/RealJokers/Issues-And-Problems
