### ISSUE TITLE
I see, You wanna learn Python. Lemme help

### ISSUE THREAD

**Issue by MackyCoders** [Deus-Scissuras/Unblocked-links-reborn#12]
No problem, I can help you learn Python in just one issue if u want.

**Comment by Deus-Scissuras** [comment]
I’m good I learned it By now

**Comment by Deus-Scissuras** [comment]
Could you make issues on My organization Repo called Issues And Problems.

**Comment by Deus-Scissuras** [comment]
Unblock Project Goggle Dev On discord @MackyCoders
