### ISSUE TITLE
Why hackers hack

### ISSUE THREAD

**Issue by MackyCoders** [Deus-Scissuras/Unblocked-links-reborn#15]
Hecker: Lets heck MeepCity so we get famous
Hecker: *hecks it*
Everyone: OMG IT IS HECKED
Hecker: *gets famous*
Everyone: OMG COOL HECKER

**Comment by Deus-Scissuras** [comment]
Your talking bout Tubers93 he probably had a object that The dev of meel city Placed in for a update but the object had a hidden malware script

**Comment by Deus-Scissuras** [comment]
I can’t talk I have FB practice

**Comment by Deus-Scissuras** [comment]
Funny Meme tho

**Comment by MackyCoders** [comment]
@Deus-Scissuras Mr. Deus-Scissuras

**Comment by Deus-Scissuras** [comment]
@MackyCoders Sorry I was at practice
