### ISSUE TITLE
Go make an actual game and put it at the top (not making a WW3 again)

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Unblocked-links-reborn#4]
If you want to make actual money or make something actually amazing I recommend u go make a game bro

**Comment by Deus-Scissuras** [comment]
My current project is a mod menu for kahoot

**Comment by Deus-Scissuras** [comment]
And after that Project Goggle A web Browser with a integrated proxy network

**Comment by NotLexer9** [comment]
what how will you even make a mod menu bruh

**Comment by Deus-Scissuras** [comment]
I'm learning
