### ISSUE TITLE
Realhack1 forced his teach to m*Ake love to him

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Unblocked-links-reborn#6]
Ayo

**Comment by NotLexer9** [comment]
Realhack1 you need to go to jail

**Comment by Deus-Scissuras** [comment]
Yea but proof?

**Comment by NotLexer9** [comment]
Here is proof

**Comment by NotLexer9** [comment]
Realhack1 is a 14 year old kid known for not paying his coders his name is David and he is known for attacking teachers and getting away with it by using usernames like realja

**Comment by Deus-Scissuras** [comment]
Lol but I lied about my info
